bump security vulnerabilities
rbkmoney/dark-api pull request #80
Opened 2020-10-28 08:22 UTC by karleowne

2020-10-28 08:39 UTC, karleowne commented on src/test/java/com/rbkmoney/dark/api/service/QuestionaryServiceTest.java
>  public class QuestionaryServiceTest {
вот эта хуета флапает полностью

2020-10-28 08:43 UTC, PospolitaNV requested changes

2020-10-28 08:43 UTC, PospolitaNV commented on pom.xml
> +        <analytics-proto.version>1.12-3b71837</analytics-proto.version>
мы же решили так не делать
https://mattermost.rbkmoney.com/matternot/pl/mryhn14ej7nqzex3bewdwdbb8r

2020-10-28 08:50 UTC, tolkonepiu commented on src/test/java/com/rbkmoney/dark/api/service/QuestionaryServiceTest.java
>  public class QuestionaryServiceTest {
Я как понимаю, MockTBaseProcessor создается в QuestionaryTestData. Используй при его создании конструктор:
```java
MockTBaseProcessor(MockMode mode, int maxStringLength, int maxContainerSize)
```
в maxContainerSize укажи 1, остальное по желанию.

2020-10-28 08:54 UTC, karleowne commented on pom.xml
> +        <analytics-proto.version>1.12-3b71837</analytics-proto.version>
😣

2020-10-28 12:33 UTC, tolkonepiu commented
@karleowne исправил бесконечную рекурсию, которая у нас возникает при заполнении InternationalBankAccount, внутри которого есть ссылка на InternationalBankAccount снова.
Плюс видимо после бампа swag моделей, поломались типы из-за рандомного генерации.

2020-10-28 12:35 UTC, tolkonepiu commented
@karleowne отсалось только версию ${shared.resources.version} починить

2020-10-28 12:35 UTC, karleowne commented
> @karleowne исправил бесконечную рекурсию, которая у нас возникает при заполнении InternationalBankAccount, внутри которого есть ссылка на InternationalBankAccount снова.
> Плюс видимо после бампа swag моделей, поломались типы из-за рандомного генерации.

@tolkonepiu сваг спецом не бампал

2020-10-28 12:37 UTC, tolkonepiu commented
@karleowne а, ок. Тогда хз, как раньше работало, но при рандомном заполнении swag моделей, рандомно выставлялись типы, в результате class cast exception. Выставил типы после рандомной генерации, должно помочь.

2020-10-28 12:42 UTC, tolkonepiu commented
@karleowne ошибка вот здесь сейчас:
```xml
                    <resourceBundles>
                        <resourceBundle>com.rbkmoney:shared-resources:${shared.resources.version}</resourceBundle>
                    </resourceBundles>
```
тут лучше вернуть версию в проперти

2020-10-29 09:36 UTC, karleowne commented
![image](https://user-images.githubusercontent.com/19729841/97550932-e2ab4a80-1a04-11eb-9e88-ff09e69b7e52.png)
тут готово , но чет jenkins

2020-10-29 09:50 UTC, PospolitaNV approved these changes

2020-10-29 12:27 UTC, tolkonepiu requested changes
Антимердж

2020-10-29 12:42 UTC, tolkonepiu approved these changes

2020-10-29 12:43 UTC, merged